name: Build rootfs Packages

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - uses: actions/checkout@v3

    - name: Install Build deps
      run: |
        sudo sed -i 's/^# \(deb-src .*\)/\1/' /etc/apt/sources.list
        sudo apt update
        sudo dpkg --force-all -r libunwind-dev
        sudo apt build-dep -y --fix-broken linux linux-meta
        sudo apt install -y libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm
        sudo locale-gen en_US.UTF-8

    - name: Build rootfs
      run: |
        mv config .config
        CFLAGS=-Wno-stringop-overflow CXXFLAGS=-Wno-stringop-overflow make

    - uses: actions/upload-artifact@v3
      with:
        name: rootfs
        path: |
          images/**
        if-no-files-found: error